name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          

      - name: Build Docker image
        run: |
          docker build -t laksma36/html-site:latest .

      - name: Push Docker image
        run: |
          docker push laksma36/html-site:latest
